id: IE9DCAC93
ocr_import_info:
  bdrc_scan_id: W1KG15996
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-09-12 14:04:05.879285
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15996
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15996
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་དབང་སྦྱིན་པ་ནོར་བུའི་རང་རྣམ།
  languages:
  - bo
  author: གྲུབ་དབང་སྦྱིན་པ་ནོར་བུ།
bases:
  I1KG16000:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16000
      total_pages: 530
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG16000.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
